P=game1
CFLAGS = `pkg-config --cflags sdl2 SDL2_image` -D_DEFAULT_SOURCE -g -O2 -std=c99 -Wall -ansi
LDLIBS = `pkg-config --libs sdl2 SDL2_image`
CC = gcc

all: $(P)

$(P): main.c
	$(CC) $(CFLAGS) $(LDLIBS) main.c -o $(P) #-c make the `made file` nonexecutable

clean:
	rm -f game1.o game1

push:
	@if [ "x$(MSG)" = 'x' ] ; then echo "Usage: MSG='whatever.' make push"; fi
	@test "x$(MSG)" != 'x'
	git commit -a -m "$(MSG)"
	git push

pull:
	git pull
